### PR TITLE
Revert "RHBA-662 - Fix group ID. (#3)"

### PR DESCRIPTION
**Pull request by ryanzhang**
This reverts commit fb4d6a05d45fafdd8a35f435f99a284b92c58703.

As we discussed,  let's keep the rhba as groupid identify for the moment.

### CODE REVIEW

**Comment by antncl** [comment]
@ryanzhang I'm worried that keeping this "for the moment" will result in it staying like this for the foreseeable future. I actually prefer com.redhat.rhba anyway. I'm fine reverting it "for the moment" if there's a need, but lets not lose track of this. I don't think the group ID should be rhpam, since the suite is still rhba.

**Comment by pszubiak** [comment]
@AntStephenson @ryanzhang  +1 for com.redhat.rhba. Would it work for nightly?

**Comment by mareknovotny** [comment]
it is wrong to encode there direct product shortcut IMHO as we saw the change happens too many times.
**com.redhat.ba** as **rhba** contains already redhat before a dot ;) and from Prakash's explanation the wrapping name is BA not RHBA ;)

**Comment by mareknovotny** [comment]
@ryanzhang what is the reason to revert this change? if we should do it correctly we need to change it anyway from **org.jboss.*** or **org.*** to **com.redhat.\<universal-product-label\>**
So this is causing some pain for build? Btw the renaming part should be ready for ER3 as we are heading really quickly into CR

**Comment by pszubiak** [comment]
Good idea with using more universal label like ba here. Hope that portfolio/suite name won't change so often like product.

**Review by mareknovotny — APPROVED** [review]
postponing discussion to later and merging this.

@ryanzhang will handle renaming properly after ER3

**Pull request merged**
